version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379" 

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  authdb:
    container_name: authdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=AuthService
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    restart: always
    ports:
      - "5050:5050"
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - ASPNETCORE_URLS=http://*:8000
      - AuthSettings:AuthUrl=http://auth.api:8004
    depends_on:
      - catalogdb
    ports:
      - "8000:8000"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - ASPNETCORE_URLS=http://*:8001
      - AuthSettings:AuthUrl=http://auth.api:8004
    depends_on:
      - basketdb
    ports:
      - "8001:8001"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin123;"
      - ASPNETCORE_URLS=http://*:8002
      - AuthSettings:AuthUrl=http://auth.api:8004
    depends_on:
      - discountdb
    ports:
      - "8002:8002"

  auth.api:
    container_name: auth.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=authdb;Port=5431;Database=AuthService;User Id=admin;Password=admin123;"
      - ASPNETCORE_URLS=http://*:8004
      - AuthSettings:AuthUrl=http://auth.api:8004
    depends_on:
      - authdb
    ports:
      - "8004:8004"

  apigateway:
    container_name: gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8003
      - AuthSettings:AuthUrl=http://auth.api:8004
    ports:
      - "8003:8003"